from frappe import _

def get_data():
    return [
        {
            "module_name": "Investment Core",
            "type": "module",
            "label": _("Investment Core"),
            "color": "#24963E",
            "icon": "octicon octicon-graph",
            "description": "Fund master, share classes, series, fee structures",
        },
        {
            "module_name": "Mutual Funds",
            "type": "module",
            "label": _("Mutual Funds"),
            "color": "#1F7B4C",
            "icon": "octicon octicon-pie-graph",
            "description": "AMC operations, scheme management, NAV, SIP/SWP",
        },
        {
            "module_name": "Portfolio Management Services",
            "type": "module",
            "label": _("PMS"),
            "color": "#1A6B3E",
            "icon": "octicon octicon-briefcase",
            "description": "Discretionary, non-discretionary, advisory PMS",
        },
        {
            "module_name": "Alternative Investment Funds",
            "type": "module",
            "label": _("AIF"),
            "color": "#155934",
            "icon": "octicon octicon-organization",
            "description": "Cat I/II/III funds, drawdowns, waterfall",
        },
        {
            "module_name": "Private Equity",
            "type": "module",
            "label": _("Private Equity"),
            "color": "#11492A",
            "icon": "octicon octicon-rocket",
            "description": "Deal pipeline, cap tables, exits",
        },
        {
            "module_name": "Venture Capital",
            "type": "module",
            "label": _("Venture Capital"),
            "color": "#0E3C22",
            "icon": "octicon octicon-light-bulb",
            "description": "Deal sourcing, DD, ESOP, portfolio monitoring",
        },
        {
            "module_name": "Bonds & Fixed Deposits",
            "type": "module",
            "label": _("Bonds & FD"),
            "color": "#2C5F2D",
            "icon": "octicon octicon-credit-card",
            "description": "Bond issuance, NCDs, FD management, coupon payments",
        },
        {
            "module_name": "Real Estate Funds",
            "type": "module",
            "label": _("Real Estate"),
            "color": "#3D6B35",
            "icon": "octicon octicon-home",
            "description": "REITs, InvITs, property-level accounting",
        },
        {
            "module_name": "Stock Broking",
            "type": "module",
            "label": _("Stock Broking"),
            "color": "#4A7C3E",
            "icon": "octicon octicon-trending-up",
            "description": "Trading, margins, settlement, contract notes",
        },
        {
            "module_name": "Family Office",
            "type": "module",
            "label": _("Family Office"),
            "color": "#5C8D47",
            "icon": "octicon octicon-people",
            "description": "Multi-generational wealth, succession planning",
        },
        {
            "module_name": "Pension Funds",
            "type": "module",
            "label": _("Pension Funds"),
            "color": "#6E9E50",
            "icon": "octicon octicon-shield-check",
            "description": "NPS, PRAN, annuity, PFRDA compliance",
        },
        {
            "module_name": "Advisor Portal",
            "type": "module",
            "label": _("Advisor Portal"),
            "color": "#80AF5A",
            "icon": "octicon octicon-person",
            "description": "RIA/MFD portal, goal planning, proposals",
        },
        {
            "module_name": "Compliance & Regulatory",
            "type": "module",
            "label": _("Compliance"),
            "color": "#24963E",
            "icon": "octicon octicon-checklist",
            "description": "SEBI, RBI, FATCA/CRS, AML compliance",
        },
        {
            "module_name": "Reports & Analytics",
            "type": "module",
            "label": _("Reports & Analytics"),
            "color": "#24963E",
            "icon": "octicon octicon-graph",
            "description": "MIS, performance attribution, risk analytics",
        },
    ]
